kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: hello
  namespace: lakshmi
  uid: f9ffb313-b8c5-4fa4-a8cd-700e070f19f8
  resourceVersion: '4600613'
  generation: 1
  creationTimestamp: '2024-04-22T10:36:37Z'
  labels:
    name: hello
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2024-04-22T10:36:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:name': {}
        'f:spec':
          'f:output':
            'f:to': {}
          'f:runPolicy': {}
          'f:source':
            'f:binary': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
            'f:type': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'teeklakshmi.jfrog.io/teeklakshmi-docker/hello-spring-microservice:2.0'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Binary
    binary: {}
  runPolicy: Serial
status:
  lastVersion: 0
